version: "3"

services:

  api:
    image: mcs-api
    container_name: mcs_api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DJANGO_KEY
      - DJANGO_ENV
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  client:
    image: mcs-client
    container_name: mcs_client_container
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CLIENT_ENV
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/mcs