version: "3"

services:

  api:
    image: mcs-api
    container_name: mcs_api_container
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_KEY
      - DJANGO_ENV
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  client:
    image: mcs-client
    container_name: mcs_client_container
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - CLIENT_ENV
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
